# Site settings
title: Child Welfare Product Hub
description: A description of your website that will show up in search indexes and social media shares.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://example.gov" # the base hostname & protocol for your site
feature_image: /assets/img/feature-background.jpg
array: []

colors:
  background: '#ffffff'
  button:
    background: '#e31c3d'
    hover: '#cd2026'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  projects:
    accent: '#02bfe7'

analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: HHS    # Change this to your agency
    subagency: ACF # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - product

footer:
  image: /assets/img/logo-acf-2x.png
  twitter:
    - ACYFgov

# Build settings
markdown: kramdown
include:
  - _navigation.json
  - _facets.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
